### ISSUE TITLE
After moving a character, the camera returns to point where character was at round start.

### ISSUE THREAD

**Issue by Borkason** [rm-code/On-The-Roadside#81] opened 2016-11-29 14:23 UTC
After moving a charatcter, the camera returns to point where character was at round start.

Example:

1. Round start
2. Character at (x,y)
3. Begin move to (x+a, y+b)
4. Camera moves with character
5. End move 
6. Camera moves back to (x,y)

**Comment by rm-code** [comment] 2016-11-29 17:22
Duplicate of #43

**Closed by rm-code** 2016-11-29 17:22 UTC
Labels: Status: Duplicate
